### ISSUE TITLE
Rework `receive::v2`, `send::v2` submodule into additive `crate::v2` and `crate::v1` submodules features

### ISSUE THREAD

**Issue by DanGould** [payjoin/rust-payjoin#392]
I don't really love how the features are laid out inside receive especially. Send is not as big of a deal because the state machine has been flattened. If there were separate modules for separate features I think they'd be easier to reason about from docs.rs

Consider removing the `not(feature = v2)` feature since we want to discourage its use and one can replicate v1 soverignty by running both a directory and payjoin client on the same machine. Rust features [should be additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification).

- [x] separate `send::{v1, v2}` modules #464
- [x] Fix PjUriBuilder feature mess #466
- [x] Place `receive` v1 typestate machine into `receive::v1` module with feature-gated visibility
- [x] Separate `receive::{v1, v2}` errors (related: #312,) #482
- [x] #490

---
follow ups:
#500

**Comment by DanGould** [comment]
@nothingmuch I believe making `PjUriBuilder::new` into variants rather than a feature-gated set of arguments  with the same method, perhaps `v1::PjUriBuilder` / `v2::PjUriBuilder` if it can't be entirely contained in the receiver state machine? is the last remaining TODO item to make the v1/v2 features additive. What's the status of that refactor?
